### ISSUE TITLE
User has no way to see or edit block list after onboarding

### ISSUE THREAD

**Issue by chiubaka** [Royl0406/Crabodoro#36]
Right now after the user completes onboarding there's no way to double-check the block list or to edit it!

**Comment by Royl0406** [comment]
Perhaps we could remove the step of setting a block list from the onboarding phase. So the onboarding phase would only require entering username. We could then move the settings button to the main menu and adapt the settings.html

**Comment by chiubaka** [comment]
I think I would recommend adding a button that leads people to the existing "Settings" page, but keep the block list as part of onboarding. Ideally, you re-use the `settings.html` page for both cases, so users are pushed there both during onboarding and whenever they hit the settings button from the pop-up.

Otherwise, exactly _what_ is blocked will be an immediate confusion for your users, and the purpose of your Chrome Extension may also not be immediately clear.
