### ISSUE TITLE
Set up Webpack for this project

### ISSUE THREAD

**Issue by chiubaka** [Royl0406/Crabodoro#46]
Required for #45. We had previously tried a few "quick and dirty" methods of getting Sentry integrated, but ran into some roadblocks.

The most "standard" way to do this would ordinarily be to just install Sentry through NPM and then import it in project files as normal. However, this project isn't currently set up to bundle JavaScript and include dependencies... and Chrome will otherwise get confused searching for `node_modules` or trip on code that wasn't compiled / transpiled for distribution as a Chrome Extension.

Solution is to use Webpack to actually compile and transform all code in this project.

I have a sample project I'm playing with [here](https://github.com/chiubaka/browser-extension-sample) where I'm testing some of these ideas, though that project does also use Nx and a few other tools we haven't discussed. I was able to get a Chrome Extension template set up with React, TypeScript, and Webpack all pretty quickly, though. Getting Sentry integrated was simple from there.

Stumbling blocks for getting Webpack integrated in _this_ project are:
- [x] This project is currently set up to have many, _many_ disparate HTML pages, whereas Webpack usually expects to create a single-page application
  - We may be able to get around this with `html-webpack-plugin`, and just output several mini-bundles, one per page
- [x] `background.js` needs to be separately bundled as a "chunk" or output for Webpack and then referenced by `manifest.json`
- [x] Need to be sure we can get a working Webpack config _without_ Nx

**Comment by Royl0406** [comment]
We've created entry points for js files and used webpack plugin for HTML files. We encountered the error that xp and coin are undefined when we attempt to navigate between crabspace and shop menu. We still need to get the images and CSS to output.

**Comment by chiubaka** [comment]
Here's some info about how to get the HTML loading with images pulled out of HTML assets: https://requestmetrics.com/web-performance/optimizing-static-html-images-webpack

Idea is to use `html-loader` and then an assets loader to get Webpack to automatically pull the images out and include them in `dist`.
